# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "uas" "usb_storage" "sd_mod" "sdhci_pci" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/eaedb4fc-7c9c-4f48-a4ce-9a6ab3d25956";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/419C-3230";
      fsType = "vfat";
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/d99de255-0d4b-4857-b09c-9a0261cf3a4e";
      fsType = "ext4";
    };

  fileSystems."/mymedia" =
    { device = "/dev/disk/by-uuid/7ca63c29-6418-4b08-b8dc-5759725466f6";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/544ad6c1-6dd4-44af-9d62-f0a717dd0d7d"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
